sudo: required
services:
  - docker

before_install:
  - docker build -t griffenclark/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true griffenclark/docker-react npm run test -- --coverage

